# Importar imágen base de python
FROM python:3.12-slim

# Instalar curl para el healthcheck de Docker
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Crear carpeta de trabajo en el contenedor
WORKDIR /app

# Copiar los requerimientos al contenedor
COPY requirements.txt .

# Instalar las dependencias de FastAPI
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del servidor
COPY ./app ./app

# Exponer el puerto de trabajo
EXPOSE 8000

# Indica comando que debe ejecutarse para levantar el servidor
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]